seer:
	nvcc collect_with_algo.cu -lcudnn -lcublas -std=c++11 -arch=compute_61 -code=sm_61 -o collect_with_algo
	nvcc collect_without_algo.cu -lcudnn -lcublas -std=c++11 -arch=compute_61 -code=sm_61 -o collect_without_algo
